# Generated by Django 5.1.7 on 2025-04-17 09:10

import crud_event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evenement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_event', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=crud_event.models.file_path)),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='personne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('num_tel', models.IntegerField()),
            ],
        ),
    ]
