# Generated by Django 5.1.7 on 2025-04-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='personne',
        ),
    ]
