# Generated by Django 5.1.7 on 2025-04-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0002_delete_personne'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
