# Generated by Django 5.1.7 on 2025-04-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0004_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='name_event',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
