# Generated by Django 5.1.7 on 2025-04-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0005_participation_name_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
