# Generated by Django 5.1.7 on 2025-04-22 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0006_participation_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='full_name',
        ),
    ]
