# Generated by Django 5.1.7 on 2025-04-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0007_remove_participation_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='participant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
