# Generated by Django 5.1.7 on 2025-04-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0009_evenement_organisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='organisateur_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
