# Generated by Django 5.1.7 on 2025-04-22 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0010_evenement_organisateur_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='name',
            new_name='participantId',
        ),
    ]
