# Generated by Django 5.1.7 on 2025-04-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0010_alter_evenement_organisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
