# Generated by Django 5.1.7 on 2025-04-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0011_rename_name_participation_participantid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='participantId',
            new_name='participan',
        ),
    ]
