# Generated by Django 5.1.7 on 2025-04-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0011_evenement_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='fullname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
