# Generated by Django 5.1.7 on 2025-04-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0012_rename_event_id_participation_event_and_more'),
        ('crud_event', '0013_alter_evenement_fullname'),
    ]

    operations = [
    ]
