# Generated by Django 5.1.7 on 2025-04-25 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0014_merge_20250424_2040'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='evenement',
        #     name='fullname',
        # ),
        migrations.RemoveField(
            model_name='evenement',
            name='organisateur',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='organisateur_name',
        ),
        migrations.AlterField(
            model_name='participation',
            name='date_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
