# Generated by Django 5.1.7 on 2025-04-25 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0015_remove_evenement_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='fullname',
        ),
    ]
