# Generated by Django 5.1.7 on 2025-04-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0017_evenement_organisateur_evenement_organisateur_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
