# Generated by Django 5.1.7 on 2025-04-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0018_evenement_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='Conne',
            field=models.BooleanField(default=False),
        ),
    ]
