# Generated by Django 5.1.7 on 2025-04-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0019_evenement_conne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='Conne',
        ),
    ]
