# Generated by Django 5.1.7 on 2025-05-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0021_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
