# Generated by Django 5.1.7 on 2025-05-01 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0022_participation_email_alter_paiement_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_event.participation'),
        ),
    ]
