# Generated by Django 5.1.7 on 2025-05-04 17:40

import crud_event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0024_paiement_participation_alter_paiement_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='nombre_participants',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.ImageField(blank=True, default='media/ibm.jpg', null=True, upload_to=crud_event.models.file_path),
        ),
    ]
