# Generated by Django 5.1.7 on 2025-05-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0025_evenement_nombre_participants_alter_evenement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='nombre_participants',
            field=models.IntegerField(),
        ),
    ]
