# Generated by Django 5.1.7 on 2025-05-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0026_alter_evenement_nombre_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='nombre_participants',
        ),
    ]
