# Generated by Django 5.1.7 on 2025-05-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0027_remove_evenement_nombre_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='nombre_places',
            field=models.IntegerField(default=0),
        ),
    ]
