# Generated by Django 5.1.7 on 2025-05-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0028_evenement_nombre_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='nombre_places',
            field=models.IntegerField(default=2),
        ),
    ]
