# Generated by Django 5.1.7 on 2025-05-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0030_evenement_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='created_by',
        ),
    ]
