# Generated by Django 5.1.7 on 2025-05-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0031_remove_evenement_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
