# Generated by Django 5.1.7 on 2025-05-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0032_evenement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
        ),
    ]
