# Generated by Django 5.1.7 on 2025-05-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0033_paiement_amount_alter_evenement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='nombre_participants',
            field=models.IntegerField(default=0),
        ),
    ]
