# Generated by Django 5.1.7 on 2025-05-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0035_organisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisateur',
            name='description',
        ),
    ]
