# Generated by Django 5.1.7 on 2025-05-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_event', '0036_remove_organisateur_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisateur',
            name='email',
            field=models.EmailField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='nom',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='prenom',
            field=models.CharField(default='', max_length=200),
        ),
    ]
