# Generated by Django 5.1.7 on 2025-04-04 11:19

import gestion_des_evenements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_des_evenements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='completed',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=gestion_des_evenements.models.file_path),
        ),
    ]
