# Generated by Django 5.1.7 on 2025-04-05 01:36

import django.db.models.deletion
import gestion_des_evenements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_des_evenements', '0002_remove_todoitem_completed_todoitem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='personne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('num_tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='billet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='compte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('mot_de_passe', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='evenement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=gestion_des_evenements.models.file_path)),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_des_evenements.personne')),
            ],
            bases=('gestion_des_evenements.personne',),
        ),
        migrations.CreateModel(
            name='organisateur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_des_evenements.personne')),
            ],
            bases=('gestion_des_evenements.personne',),
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_des_evenements.personne')),
            ],
            bases=('gestion_des_evenements.personne',),
        ),
    ]
