# Generated by Django 5.1.7 on 2025-04-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_des_evenements', '0003_personne_billet_compte_evenement_delete_todoitem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='billet',
        ),
        migrations.DeleteModel(
            name='compte',
        ),
        migrations.DeleteModel(
            name='organisateur',
        ),
    ]
