# Generated by Django 5.1.7 on 2025-04-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_des_evenements', '0004_delete_billet_delete_compte_delete_organisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='personne_ptr',
        ),
        migrations.DeleteModel(
            name='evenement',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='personne_ptr',
        ),
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.DeleteModel(
            name='personne',
        ),
        migrations.DeleteModel(
            name='utilisateur',
        ),
    ]
